(package "lsp-docker"
         "1.0.0"
         "LSP Docker integration")

(package-file "lsp-docker.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "dash")
(depends-on "lsp-mode")
(depends-on "f")
(depends-on "s")
(depends-on "yaml")
(depends-on "ht")
(depends-on "async")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
